import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from "@/components/Navbar";
import 'tailwindcss/tailwind.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dato CMS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
